apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Recycle